.NH 2
.XN Domain-specific language
.LP
The FBDL is a domain-specific language with its own syntax.
Some of the register-centric tools are built on top of standard file formats or makrkup languages such as JSON, TOML, XML or YAML.
Such an approach allows for fast prototyping and has lower entry threshold.
However, it becomes a burden when more conceptually advanced features, for example parametrization, have to be supported.
The description quickly begins to gain in volume and the overall feeling is it is needlessly verbose.
What is more, having its own adjusted language syntax allows for more informative compiler error messages.
