.bp
.NH
.XN Functionalities
.LP
Each element property must have concrete type.
The default value of each property is specified in the round brackets ().
If the default value is \fCbus width\fR, then it means that the default value equals the actual value of the bus \fCwidth\fR property.
If the default value is \fCundefined\fR, then ...
If the target language for the provider code does not have a concept of undefined value, then values such as 0, \fCNull\fR, \fCNone\fR, \fCnil\fR etc. shall be used.
