.NH 2
.XN Memory
.LP
The \fCmemory\fR functionality has following properties:
.IP "\f[CB]size\f[CW] integer (obligatory)\f[]" 0.2i
The \fCsize\fR property determines the \fCmemory\fR size.
The \fCsize\fR is in the number of memory words with width equal to the \fCmemory\fR \fCwidth\fR property value.
.IP "\f[CB]width\f[CW] integer (bus width)\f[]"
The \fCwidth\fR property determines the memory data width.
