== Blackbox

The `blackbox` functionality is used to incorporate blocks implemented manually or generated by external tools.
For example, a user may want to explicitly manage some particular registers' layouts.
In such a case, a register-centric tool might be used, and the generated block can be incorporated into the wrapping functionality-centric description using the `blackbox` functionality.

The `blackbox` functionality has following properties:

*`size`*` integer (obligatory) [definitive]`
#pad(left: 1em)[
The `size` property defines size of the `blackbox` in the number of words with width equal to the `width` property value of the block in which `blackbox` is defined.
]

The code generated for the requester should not provide any means for accessing the `blackbox`.
The code generated for the provider must provide a means to connect the `blackbox` to the remaining part of the bus generated by an FBDL compiler.
